#!/bin/sh

progname=${0##*/}

if [ -e "./lib/jailer-core" ]; then
    LIB="./lib"
elif [ -e "/usr/local/lib/jailer" ]; then
    LIB="/usr/local/lib/jailer"
else
    echo "unable to locate jailer libraries"
    exit 1
fi

# set global variables
COLOUR_SET_R="\033[0;31m"
COLOUR_SET_G="\033[0;32m"
COLOUR_SET_Y="\033[0;33m"
COLOUR_SET_B="\033[0;34m"
COLOUR_SET_M="\033[0;35m"
COLOUR_SET_C="\033[0;36m"
COLOUR_SET_W="\033[0;37m"
COLOUR_END="\033[0m"

# load libs (before jailer-base)
. "${LIB}/jailer-cmd"
. "${LIB}/jailer-core"
. "${LIB}/jailer-exception"
. "${LIB}/jailer-help"
. "${LIB}/jailer-init"
. "${LIB}/jailer-net"
. "${LIB}/jailer-util"
. "${LIB}/jailer-zfs"

# entry point
. "${LIB}/jailer-base"
