#!/bin/sh

progname=${0##*/}

if [ -e "./lib/jailer-core" ]; then
    LIB="./lib"
elif [ -e "/usr/local/lib/jailer" ]; then
    LIB="/usr/local/lib/jailer"
else
    echo "unable to locate jailer libraries"
    exit 1
fi

# load libs (before jailer-base)
#
. "${LIB}/jailer-cmd"
#. "${LIB}/jailer-config"
. "${LIB}/jailer-core"
#. "${LIB}/jailer-datastore"
. "${LIB}/jailer-exception"
. "${LIB}/jailer-help"
#. "${LIB}/jailer-info"
. "${LIB}/jailer-init"
. "${LIB}/jailer-net"
#. "${LIB}/jailer-rctl"
. "${LIB}/jailer-util"
. "${LIB}/jailer-zfs"
#
# entry point
. "${LIB}/jailer-base"
