#!/bin/sh

if [ -e "./lib/jailio-core" ]; then
    LIB="./lib"
elif [ -e "/usr/local/lib/jailio" ]; then
    LIB="/usr/local/lib/jailio"
else
    echo "unable to locate jailio libraries"
    exit 1
fi

# load libs
. "${LIB}/jailio-cmd"
. "${LIB}/jailio-help"
. "${LIB}/jailio-init"
#. "${LIB}/jailio-config"
. "${LIB}/jailio-core"
#. "${LIB}/jailio-datastore"
#. "${LIB}/jailio-info"
#. "${LIB}/jailio-rctl"
. "${LIB}/jailio-util"
. "${LIB}/jailio-zfs"

. "${LIB}/jailio-base"
