#!/bin/sh

progname=${0##*/}

if [ -e "./lib/jailer-core" ]; then
    LIB="./lib"
elif [ -e "/usr/local/lib/jailer" ]; then
    LIB="/usr/local/lib/jailer"
else
    echo "unable to locate jailer libraries"
    exit 1
fi

# set global variables
COLOUR_SET_R="\033[0;31m"
COLOUR_SET_G="\033[0;32m"
COLOUR_END="\033[0m"

# load libs (before jailer-base)
. "${LIB}/jailer-cmd"
. "${LIB}/jailer-core"
. "${LIB}/jailer-exception"
. "${LIB}/jailer-help"
. "${LIB}/jailer-init"
. "${LIB}/jailer-net"
. "${LIB}/jailer-util"
. "${LIB}/jailer-zfs"

# entry point
. "${LIB}/jailer-base"
