#!/bin/sh

help::parse_help(){
  case "${1}" in
    create)   help::create  ;;
    edit)     help::edit    ;;
    nat)      help::nat     ;;
    rdr)      help::rdr     ;;
    *)        util::usage   ;;
  esac
}

help::create(){
  cat << EOT
Usage:  jailer create  [-r version | -s snap] [-t eb|ng] [-b bridge] [-n] [-d domain] [-g gateway -m netmask] [-a addr] [name]
Options:
  -r version          : FreeBSD-version as base of Jail; defaults to uname -r
  -s snapshot         : Clone from snapshot as base of Jail
  -n                  : Make Jail less noisy
  -d domain           : Set Jail's domain
  -t network_type     : Network Type; defaults to none, can be eb (epair/bridge) or ng (netgraph)
  -b bridge|interface : Attach to bridge
  -g gateway          : Set Jail's gateway
  -m netmask          : Netmask (if specifying a Gateway)
  -a addr             : Use addr as address or dhcp to use dhclient in Jail
EOT
  exit 0
}

help::edit(){
  cat << EOT
Usage: jailer edit jail
EOT
  exit 0
}

help::nat(){
  cat << EOT
Usage jailer nat ...
  list [jail]
  add -i interface [ -a my.second.ip.addr ] jail
  del jail
EOT
  exit 0
}

help::rdr(){
  cat << EOT
Usage: jailer rdr ...
  list [jail]
  add -i interface [ -a my.second.ip.addr ] [ -p tcp|udp -r recvport [ -d destport ] ] jail
  del -j jail [ -i rule_index | -f ] ; -f deletes all rules for jail
EOT
  exit 0
}

help::edit(){
  cat << EOT
Usage: jailer edit name
EOT
  exit 0
}
