#!/bin/sh

jail::exception::bootstrap() {
  zfs destroy ${JAILER_ZFS_DATASET}/bootstrap/${_version}
  rm ${jailer_dir}/bootstrap/dist-files/base-${_version}.txz > /dev/null 2>&1
  util::err "bootstrap failed, try again later"
}
