#!/bin/sh

net::rdr_parse() {
  [ $# -eq 0 ] && help::rdr
  shift
  case "${1}" in
    list)   net::rdr_list "$@"  ;;
    add)    net::rdr_add "$@"   ;;
    del)    net::rdr_del "$@"   ;;
  esac
}

net::nat_parse(){
  [ $# -eq 0 ] && help::nat
  shift
  case "${1}" in
    list)   net::nat_list "$@"  ;;
    add)    net::nat_add "$@"   ;;
    del)    net::nat_del "$@"   ;;
  esac
}

net::rdr_list(){
  _name="$1"
  if [ -z "${_name}" ]; then
    cat /etc/jail.conf.d/.pf.rdr.jailer.conf
    exit 0
  fi
  if !(grep " ${_name}\$" /etc/jail.conf.d/.pf.rdr.jailer.conf); then
    echo "No rule found for ${_name}"
    exit 1
  fi
}

net::rdr_add() {
  local _name _recvport _destport _interface _addr

  while getopts :i:r:d:a:p: _opt; do
    case ${_opt} in
      a)  _addr="${OPTARG}"       ;;
      i)  _interface="${OPTARG}"  ;;
      p)  _proto="${OPTARG}"      ;;
      r)  _recvport="${OPTARG}"    ;;
      d)  _destport="${OPTARG}"   ;;
      *)  help::rdr               ;;
    esac
  done
  shift $((OPTIND - 1))

  _name="${1}"
  jail::checkexists ${_name}
  _jaddr=$(jexec ${_name} ifconfig $(jexec ${_name} ifconfig -g epair) | awk '/inet / {print $2}')

  ## Error handling
  [ -z "${_interface}" ] && util::err "Please specify interface with -i"
  [ -z "${_recvport}" ] && [ -z "${_addr}" ] && util::err "Please redirect by specifying a port (-r 80 -p tcp) or an address (-a my.second.ip.addr)"
  [ ! -z "${_recvport}" ] && [ -z "${_proto}" ] && util::err "Please specify protocol with -p; e.g. -p tcp, -p udp"
  [ -z "${_destport}" ] && [ -n "${_recvport}" ] && _destport="${_recvport}"

  ## Constructing redirection rule
  _rdrbegin="rdr pass on ${_interface} inet"
  [ ! -z "${_proto}" ] && _rdrproto="proto ${_proto}"
  _rdrfrom="from any"
  _rdrtoaddr="to ${_addr}"
  [ -n "${_recvport}" ] && _rdrtoport="port ${_recvport}"
  _rdrdestaddr="-> ${_jaddr}"
  [ -n "${_destport}" ] && _rdrdestport="port ${_destport}"
  _rule="${_rdrbegin} ${_rdrproto} ${_rdrfrom} ${_rdrtoaddr} ${_rdrtoport} ${_rdrdestaddr} ${_rdrdestport}"
  _index=$(expr $(
    ( grep -so -e '#\S*' /etc/jail.conf.d/.pf.rdr.jailer.conf || echo '#0' ) |
    sort -h |
    tail -1 |
    tr -d '#'
    ) + 1
  )
  ( echo ${_rule} | pfctl -nf- ) && \
  echo "${_rule} #${_index} ${_name}" >> /etc/jail.conf.d/.pf.rdr.jailer.conf && \
  /usr/sbin/service pf reload
}

net::rdr_del() {
  while getopts :fi: _opt; do
    case ${_opt} in
      i)  _index="${OPTARG}"  ;;
      f)  _flush="yes"        ;;
      *)  help::rdr           ;;
    esac
  done
  shift $((OPTIND - 1))
  _jail="${1}"

  if grep ${_jail} /etc/jail.conf.d/.pf.rdr.jailer.conf; then
    [ -z "${_jail}" ] && util::err "Please specify jail with -j jailname"
    [ -n "${_index}" ] && sed -i ".$(date +%s)" -e "/#${_index} ${_jail}\$/d" /etc/jail.conf.d/.pf.rdr.jailer.conf && \
      /usr/sbin/service pf reload
    [ -n "${_flush}" ] && sed -i ".$(date +%s)" -e "/ ${_jail}\$/d" /etc/jail.conf.d/.pf.rdr.jailer.conf && \
      /usr/sbin/service pf reload
  else
    echo "No rule for ${_jail}"
    exit 1
  fi
}

net::nat_list(){
  _name="$1"
  if [ -z "${_name}" ]; then
    cat /etc/jail.conf.d/.pf.nat.jailer.conf
    exit 0
  fi
  if !(grep "#${_name}\$" /etc/jail.conf.d/.pf.nat.jailer.conf); then
    echo "No rule for ${_name}"
    exit 1
  fi
}

net::nat_add() {
  local _name _addr _interface

  while getopts :i:a: _opt; do
    case ${_opt} in
      a)  _addr="${OPTARG}"       ;;
      i)  _interface="${OPTARG}"  ;;
      *)  help::nat               ;;
    esac
  done
  shift $((OPTIND - 1))

  _name="${1}"
  jail::checkexists ${_name}
  _jaddr=$(jexec ${_name} ifconfig $(jexec ${_name} ifconfig -g epair) | awk '/inet / {print $2}')

  ## Error handling
  [ -z "${_interface}" ] && util::err "Please specify interface with -i"

  ## Constructing NAT rule
  _natbegin="nat on ${_interface} inet"
  _natfrom="from ${_jaddr} to any"
  [ ! -z "${_addr}" ] && _nataddr="-> ${_addr}" || _nataddr="-> (${_interface}:0)"
  _rule="${_natbegin} ${_natfrom} ${_nataddr}"
  ( echo ${_rule} | pfctl -nf- ) && \
  echo "${_rule} #${_name}" >> /etc/jail.conf.d/.pf.nat.jailer.conf && \
  /usr/sbin/service pf reload
}

net::nat_del(){
  local _jail

  _jail="${1}"
  [ -z "${_jail}" ] && help::nat
  if grep ${_jail} /etc/jail.conf.d/.pf.nat.jailer.conf; then
    sed -i ".$(date +%s)" -e "/#${_jail}\$/d" /etc/jail.conf.d/.pf.nat.jailer.conf && \
      /usr/sbin/service pf reload
  else
    echo "No rule for ${_jail}"
    exit 1
  fi
}

net::get_avail_addr(){
  _bridge="${1}"
  _addr=$(/usr/libexec/flua ${LIB}/lua/avail_addr.lua ${_bridge})
}
