#!/bin/sh

switch::list(){
  local _bridge
 _format="%s^%s^%s^\n"

 {
  printf "${_format}" "NAME" "DESCR" "ADDR"
  for _bridge in $(sysrc -n cloned_interfaces | tr ' ' '\n' | grep "bridge*") ;
  do
    if  ! ifconfig ${_bridge} > /dev/null  ; then
      service netif start ${_bridge} 2>&1 > /dev/null ;
    fi
    _inet=$(ifconfig -f inet:cidr bridge0 | awk '/inet/ {print $2}')
    _desc=$(ifconfig ${_bridge} | sed -n 's/\tdescription: \(\.*\)/\1/p')
    printf "${_format}" "${_bridge}" "${_desc}" "${_inet}"
  done
  } | column -ts^
}


switch::create(){
  local _name _ifname
  local _id _addr _type _mtu

  while getopts :t:m:a: _opt; do
    case ${_opt} in
      t) _type="${OPTARG}" ;;
      m) _mtu="${OPTARG}" ;;
      a) _addr="${OPTARG}" ;;
      *) util::usage ;;
    esac
  done
  shift $((OPTIND - 1))
  _name="$1"
  _ifname=$(ifconfig bridge create inet ${_addr} descr ${_name})
  sysrc ifconfig_${_ifname}="inet ${_addr} descr ${_name}"
  sysrc cloned_interfaces+="${_ifname}"
  service netif start ${_ifname}
}
