#!/bin/sh

VERSION=0.1.0
VERSION_INT=00100
VERSION_BSD=$(uname -K)
UNAME_m=$(uname -m)
UNAME_p=$(uname -p)
UNAME_r=$(uname -r)
HOSTNAME=$(hostname)
PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

cmd::parse_info "$@"

. /etc/rc.subr
load_rc_config "jailio"


[ ! -d "/etc/jail.conf.d" ] && init::jailconf && mkdir /etc/jail.conf.d
[ ! -d "/var/log/jail" ]    && mkdir /var/log/jail

zfs::init

cmd::parse "$@"
