#!/bin/sh

VERSION=0.1.0
VERSION_INT=00100
VERSION_BSD=$(uname -K)
PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

. /etc/rc.subr
load_rc_config "jailio"

cmd::parse_info "$@"

[ ! -d "/etc/jail.conf.d" ] && init::jailconf && mkdir /etc/jail.conf.d
[ ! -d "/var/log/jail" ]    && mkdir /var/log/jail

zfs::init

cmd::parse "$@"
