#!/bin/sh


jail::list(){
  _format="%s^%s^%s\n"
  {
    printf "${_format}" "JID" "HOSTNAME" "IPv4"
    for _j in $(jls name);
    do
      _hostname=$(jexec ${_j} hostname)
      _ipaddr=$(jexec ${_j} ifconfig -f inet:cidr $(jexec ${_j} ifconfig -g epair) | awk '/inet / {print $2}')
      printf "${_format}" "${_j}" "${_hostname}" "${_ipaddr}"
    done
  } | column -ts^
}


jail::get_next_id(){
  expr $(
    ( grep -s '$id' /etc/jail.conf.d/* || echo '$id = "0";' ) |
    awk -F '[="]' '{print $3}' |
    sort -h |
    tail -1
  ) + 1
}

jail::start(){
  local _name="$1"
  jail -f /etc/jail.conf.d/${_name}.conf -c ${_name}
}

jail::stop(){
  local _name="$1"
  jail -f /etc/jail.conf.d/${_name}.conf -r ${_name}
}

jail::destroy(){
  local _name="$1"

  jail::stop ${_name}

  rm /etc/jail.conf.d/${_name}.conf &&
  sysrc jail_list-="${_name}"

  while ! {
    zfs destroy ${JAILIO_ZFS_DATASET}/${_name}@base
    sleep 5
    zfs destroy ${JAILIO_ZFS_DATASET}/${_name}
  }
  do
    echo "ZFS busy, trying again"
  done
}

jail::extract(){
  local version=$1
  mkdir -p ${jailio_dir}/bootstrap/dist-files
  [ -z ${FreeBSD_mirror} ] && FreeBSD_mirror="https://download.freebsd.org/ftp"
  ( [ -e ${jailio_dir}/bootstrap/dist-files/base-${_version}.txz ] && jail::_checksum ${_version} ) ||
  ( fetch -o ${jailio_dir}/bootstrap/dist-files/base-${_version}.txz ${FreeBSD_mirror}/releases/$(uname -m)/${_version}/base.txz && jail::_checksum ${_version} )
  tar -xf ${jailio_dir}/bootstrap/dist-files/base-${_version}.txz -C ${jailio_dir}/bootstrap/${_version}/
}

jail::_checksum(){
  local _version=$1
  sha256 -qc $(fetch -qo - ${FreeBSD_mirror}/releases/$(uname -m)/${_version}/MANIFEST | grep base.txz | cut -f 2) ${jailio_dir}/bootstrap/dist-files/base-${_version}.txz > /dev/null
}


jail::bootstrap(){
  [ "$#" -eq "0" ] && zfs list -t snap -Ho name -r ${JAILIO_ZFS_DATASET}/bootstrap | sed -e "s|${JAILIO_ZFS_DATASET}/bootstrap/||" -e 's/@base$//' && exit 0

  local _version="${1}"

  zfs create -p ${JAILIO_ZFS_DATASET}/bootstrap/${_version}
  jail::extract ${_version}
  zfs snap ${JAILIO_ZFS_DATASET}/bootstrap/${_version}@base
}

jail::create(){
  local _name _id _path
  local _version=$(uname -r) _snap
  local _addr _switch="bridge0" _domain=$(hostname)
  local _silent
  local _gw _netmask
  local _script _content

  while getopts :a:b:c:d:f:ns:r: _opt; do
    case ${_opt} in
      a) _addr="${OPTARG}" ;;
      b) _switch="${OPTARG}" ;;
      c) _content="${OPTARG}" ;;
      d) _domain="${OPTARG}" ;;
      f) _script="${OPTARG}" ;;
      n) _silent="yes" ;;
      r) _version="${OPTARG}" ;;
      s) _snap="${OPTARG}" ;;
      *) util::usage ;;
    esac
  done
  shift $((OPTIND - 1))

  _name="${1:-$(uuidgen)}"
  _id=$(jail::get_next_id)
  _path=${jailio_dir}/${_name}
  _gw=$(ifconfig -f inet:dotted ${_switch} | awk '/inet/ {print $2}')
  _netmask=$(ifconfig -f inet:dotted ${_switch} | awk '/inet/ {print $4}')
  cat << EOF > /etc/jail.conf.d/${_name}.conf
# vim: set syntax=sh:
exec.clean;
allow.raw_sockets;
mount.devfs;

${_name} {
    \$id     = "${_id}";
    \$ipaddr = "${_addr}";
    \$mask   = "${_netmask}";
    \$gw     = "${_gw}";
    \$bridge = "${_switch}";
    \$domain = "${_domain}";
    vnet;
    vnet.interface = "epair\${id}b";

    exec.prestart   = "ifconfig epair\${id} create up";
    exec.prestart  += "ifconfig epair\${id}a up descr vnet-\${name}";
    exec.prestart  += "ifconfig \${bridge} addm epair\${id}a up";

    exec.start      = "/sbin/ifconfig lo0 127.0.0.1 up";
    exec.start     += "/sbin/ifconfig epair\${id}b \${ipaddr} netmask \${mask} up";
    exec.start     += "/sbin/route add default \${gw}";
    exec.start     += "/bin/sh /etc/rc";

    exec.prestop    = "ifconfig epair\${id}b -vnet \${name}";

    exec.poststop   = "ifconfig \${bridge} deletem epair\${id}a";
    exec.poststop  += "ifconfig epair\${id}a destroy";

    host.hostname = "\${name}.\${domain}";
    path = "${_path}";
    exec.consolelog = "/var/log/jail/\${name}.log";
    persist;
}
EOF

  [ ! -z ${_snap} ]    && zfs clone ${JAILIO_ZFS_DATASET}/${_snap} ${JAILIO_ZFS_DATASET}/${_name} || ( zfs send ${JAILIO_ZFS_DATASET}/bootstrap/${_version}@base | zfs recv ${JAILIO_ZFS_DATASET}/${_name} )
  [ ! -z ${_silent} ]  && sysrc -q -f "${_path}"/etc/rc.conf cron_enable="NO" sendmail_enable="NONE" syslogd_flags="-ss"
  [ ! -z ${_content} ] && cp -a ${_content} ${_path}/tmp/

  sysrc -q jail_list+="${_name}"
  jail::start ${_name}
  [ ! -z ${_script} ]  && jail::exec -f ${_script} ${_name}
}

jail::console() {
  local _name="$1"
  jexec -l ${_name} /bin/tcsh
}

jail::exec() {
  local _name _script

  while getopts :f: _opt; do
    case ${_opt} in
      f) _script="${OPTARG}" ;;
      *) util::usage ;;
    esac
  done
  shift $((OPTIND - 1))
  _name="$1"
  jexec -l ${_name} /bin/sh -s < ${_script}
}
