#!/bin/sh

VERSION=0.1.0
VERSION_INT=00100
VERSION_BSD=$(uname -K)
UNAME_m=$(uname -m)
UNAME_p=$(uname -p)
UNAME_r=$(uname -r)
HOSTNAME=$(hostname)
PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin


. /etc/rc.subr
load_rc_config "jail"
load_rc_config "jailer"


cmd::parse_init "$@"

# Sanity Checks

[ -z "$rc_force" ] && ! checkyesno jail_enable && util::err "jail service is not enabled in /etc/rc.conf, please run 'jailer init' or enable it manually"
[ -z "${jailer_dir}" ] && util::err "jailer_dir is not set in /etc/rc.conf, please run 'jailer init' or set it manually"
grep jconfdir /etc/rc.d/jail > /dev/null || util::err "/etc/rc.d/jail is not patched, please run 'jailer init'"

# Basic Setup

[ ! -d "/etc/jail.conf.d" ] && mkdir /etc/jail.conf.d
[ ! -d "/var/log/jail" ]    && mkdir /var/log/jail

zfs::init

# Parse and Run

cmd::parse "$@"
