#!/bin/sh

jail::exception::image() {
  zfs destroy ${JAILER_ZFS_DATASET}/image/${_version}       > /dev/null 2>&1
  rm -f ${jailer_dir}/image/dist-files/base-${_version}.txz > /dev/null 2>&1
  return 1
}

jail::exception::create() {
  jail::destroy ${_name}        > /dev/null 2>&1
  ifconfig epair${_id}b destroy > /dev/null 2>&1
  util::err "jail creation failed"
}
