#!/bin/sh

util::err() {
  printf "\n${progname}: ${COLOUR_SET_R}ERROR: $1 ${COLOUR_END}\n" >&2
  exit 1
}

util::warn() {
  printf "\n${COLOUR_SET_Y}WARN:${COLOUR_END} $1\n" >&2
}

util::tbd() {
  echo "This feature is not implemented yet"
  exit 1
}

util::usage() {
    cat << EOT
Usage: jailer ...
    version
    init
    help subcommand
    image fetch [version]
    image list [version]
    image list remote
    image use [version]
    create  [-D] [-r version | -s snap] [-n] [-d domain]
            [-b bridge] [-t eb|ng] [-g gateway -m netmask] [-a addr] [name]
    destroy name
    list
    start [name ...]
    stop [-f] [name ...]
    console name
    snap jail[@name]
    nat list [jail]
    nat add -i interface [ -a my.second.ip.addr ] jail
    nat del jail
    rdr list [jail]
    rdr add -i interface [ -a my.second.ip.addr ] [ -p tcp|udp -r recvport [ -d destport ] ] jail
    rdr del -j jail [ -i rule_index | -f ] ; -f deletes all rules for jail
EOT
    exit 1
}

util::version(){
  printf "v%s\nr%s\n" ${VERSION} ${VERSION_INT}
}


