#!/bin/sh

util::err() {
  echo "${0}: ERROR: $1" >&2
  exit 1
}

util::tbd() {
  echo "This feature is not implemented yet"
  exit 1
}

util::version(){
  printf "v${VERSION}\nr${VERSION_INT}\n"
}


util::usage() {
    cat << EOT
Usage: jailio ...
    version
    init
    bridge list
    bridge create [-m mtu] [-a add/pref] [-t type] name

    bootstrap [version]

    create [-r version] [-s snap] [-b bridge] [-n|--no-noise] [-d domain] [-a addr] [-f exec.sh] [-c dir/file] name
    destroy name

    list
    start [name ...]
    stop [-f] [name ...]

    exec -f /path/to/script.sh name
    console name

    snap jail[@name]

EOT
    exit 1
}
