#!/bin/sh

VERSION=0.1.0
VERSION_INT=00100
VERSION_BSD=$(uname -K)
UNAME_m=$(uname -m)
UNAME_p=$(uname -p)
UNAME_r=$(uname -r)
HOSTNAME=$(hostname)
PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin


. /etc/rc.subr
load_rc_config "jail"
load_rc_config "jailio"


cmd::parse_init "$@"

[ -z "$rc_force" ] && ! checkyesno jail_enable && util::err "\$jail_enable is not enabled in /etc/rc.conf!"


diff ${LIB}/init/jail_confdir /etc/rc.d/jail > /dev/null || util::err "/etc/rc.d/jail not patched, please run jailio init"
[ ! -d "/etc/jail.conf.d" ] && mkdir /etc/jail.conf.d
[ ! -d "/var/log/jail" ]    && mkdir /var/log/jail

zfs::init

cmd::parse "$@"
