#!/bin/sh

util::err() {
    echo "${0}: ERROR: $1" >&2
    exit 1
}

util::tbd() {
    echo "This feature is not implemented yet"
    exit
}

util::version(){
    echo "jailio: The final word in container orchestration v${VERSION} (rev. ${VERSION_INT})"
}



util::usage() {
    util::version
    cat << EOT
Usage: jailio ...
    version
    init
    switch list
    switch create [-m mtu] [-a add/pref] [-t type] name

    bootstrap [version]

    create [-r version] [-s snap] [-b switch] [-n|--no-noise] [-d domain] [-a addr] name
    destroy name

    list
    start [name ...]
    stop [-f] [name ...]

    exec -f /path/to/script.sh name
    console name

    snap jail[@name]

EOT
    exit 1
}
