#!/bin/sh

util::err() {
  echo "${progname}: ERROR: $1" >&2
  exit 1
}

util::tbd() {
  echo "This feature is not implemented yet"
  exit 1
}

util::version(){
  printf "v%s\nr%s\n" ${VERSION} ${VERSION_INT}
}


util::usage() {
    cat << EOT
Usage: jailer ...
   version
   init
   help subcommand
   bootstrap [version]
   create [-r version | -s snap] [-n] [-t eb|ng] [-b bridge|interface] [-d domain] [-g gateway -m netmask] [-a addr] [name]
   destroy name
   list
   start [name ...]
   stop [-f] [name ...]
   console name
   snap jail[@name]
   nat list [jail]
   nat add -i interface [ -a my.second.ip.addr ] jail
   nat del jail
   rdr list [jail]
   rdr add -i interface [ -a my.second.ip.addr ] [ -p tcp|udp -r recvport [ -d destport ] ] jail
   rdr del -j jail [ -i rule_index | -f ] ; -f deletes all rules for jail
EOT
    exit 1
}
